---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Create nginx document root
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create custom index page
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>{{ inventory_hostname }}</title>
          <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              .container { max-width: 800px; margin: 0 auto; }
              h1 { color: #333; }
              .info { background: #f4f4f4; padding: 20px; border-radius: 5px; }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>Welcome to {{ inventory_hostname }}</h1>
              <div class="info">
                  <p><strong>Server:</strong> {{ inventory_hostname }}</p>
                  <p><strong>IP Address:</strong> {{ ansible_default_ipv4.address }}</p>
                  <p><strong>OS:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
                  <p><strong>Nginx Version:</strong> {{ ansible_nginx_version | default('Unknown') }}</p>
              </div>
          </div>
      </body>
      </html>
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Configure nginx basic site
  copy:
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          root /var/www/html;
          index index.html index.htm;
          
          server_name _;
          
          location / {
              try_files $uri $uri/ =404;
          }
          
          location /health {
              access_log off;
              return 200 "healthy\n";
              add_header Content-Type text/plain;
          }
      }
    dest: /etc/nginx/sites-available/default
    backup: yes
  notify: reload nginx

- name: Enable the default site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: Test nginx configuration
  command: nginx -t
  changed_when: false
