all:
  children:
    webservers:
      hosts:
        web1-prod:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
        web2-prod:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
    database:
      hosts:
        db1-prod:
          ansible_host: 10.0.1.20
          ansible_user: ubuntu
    docker_hosts:
      hosts:
        docker1-prod:
          ansible_host: 10.0.1.30
          ansible_user: ubuntu
        docker2-prod:
          ansible_host: 10.0.1.31
          ansible_user: ubuntu
