all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
        web2:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
    database:
      hosts:
        db1:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
    docker_hosts:
      hosts:
        docker1:
          ansible_host: 192.168.1.30
          ansible_user: ubuntu
        docker2:
          ansible_host: 192.168.1.31
          ansible_user: ubuntu
