---
- name: Update system packages
  package:
    name: "*"
    state: latest
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Update package cache and upgrade (Ubuntu/Debian)
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == "Debian"

- name: Install essential packages
  package:
    name:
      - curl
      - wget
      - vim
      - htop
      - git
      - unzip
      - tree
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone | default('UTC') }}"

- name: Configure MOTD
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  notify: update motd

- name: Create admin user if defined
  user:
    name: "{{ admin_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes
  when: admin_user is defined

- name: Configure SSH hardening
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
  notify: restart ssh

- name: Ensure SSH service is running
  service:
    name: ssh
    state: started
    enabled: yes
