---
# Common role variables
timezone: "America/New_York"
admin_user: "admin"

# Package lists
essential_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - unzip
  - tree
  - net-tools
  - tcpdump

# SSH configuration
ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
