---
- name: Configure Nginx Web Servers
  hosts: webservers
  become: yes
  gather_facts: yes
  
  roles:
    - nginx
  
  post_tasks:
    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Test nginx configuration
      command: nginx -t
      changed_when: false
    
    - name: Reload nginx if configuration is valid
      service:
        name: nginx
        state: reloaded
